server:
   host: localhost
   port: 10100
   
spring:
   application:
      name: @pom.artifactId@
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://${server.host}:${server.port}/eureka/
      fetch-registry: false
      register-with-eureka: false
    