server:
  port: 9411

armeria:
  ports:
    - port: 9410
      protocol: HTTP

management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka/
